baseURL = 'https://bsurmanski.ca/'
languageCode = 'en-us'
title = 'B Surmanski'
theme = "beautifulhugo"
canonifyURLs = false
enableGitInfo = true

[params]
    readingTime = true
    logo = "img001.jpg"
    mainSections = ["photography", "tech"]
    favicon = "img021.png"
    selfHosted = true
    commit = "https://github.com/bsurmanski/bsurmanskica/tree/"

[params.author]
    name = "Brandon Surmanski"
    website = "https://bsurmanski.ca"
    github = "bsurmanski"
    linkedin = "in/bsurmanski"
    500px = "bsurmanski"
    itchio = "bsurmanski"
    instagram = "bsurmanski"


[[menu.main]]
    name = "Photography"
    url = "/photography/"
    weight = 20

[[menu.main]]
    name = "Tech"
    url = "/tech/"
    weight = 20

[[menu.main]]
    name = "Gaming"
    weight = 30
    hasChildren = true
    identifier = "gaming"

[[menu.main]]
    name = "Micro Reviews"
    url = "/games/"
    parent = "gaming"
    weight = 10

[[menu.main]]
    name = "About Me"
    url = "/page/about/"
    weight = 40